// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vwegyduejazsqawtidsn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ3ZWd5ZHVlamF6c3Fhd3RpZHNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0MTIxNjksImV4cCI6MjA3MTk4ODE2OX0.gy2Nho0g8w0AzwudoTHh7TF3DBDxqG1U9pfGuP6Tsts";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});